server:
  port: 8082
  servlet:
    context-path: /
logging:
  level:
    #项目日志级别
    com.demo: debug
    #spring日志级别
    org.springframework: info
spring:
  application:
    name: user-consume
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka