server:
  port: 7081
  servlet:
    context-path: /
logging:
  level:
    #项目日志级别
    com.demo: debug
    #spring日志级别
    org.springframework: info
spring:
  application:
    name: user-consume
eureka:
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
    #拉取时长
    #fetch-remote-regions-registry: 5
#单纯ribbon
#user-server:
  #ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#全局超市时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#feign配置

feign:
  hystrix:
    enabled: true
#ribbon:
  #ConnectionTimeOut: 500
  #ReadTimeOut: 2000