server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    #项目日志级别
    com.demo: debug
    #spring日志级别
    org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima-boot-demo
    username: root
    password:
  application:
    name: user-server
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: mapper/*.xml
  type-aliases-package: com.cloud.pojo
eureka:
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
    #拉取时长
    #fetch-remote-regions-registry: 5
  #配死服务
  #instance:
    #prefer-ip-address: true
    #ip-address: 127.0.0.1