server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    #项目日志级别
    com.demo: debug
    #spring日志级别
    org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima-boot-demo
    username: root
    password:
  application:
    name: user-server
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: mapper/*.xml
  type-aliases-package: com.cloud.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka