server:
  port: 10087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true
  server:
    enable-self-preservation: true
    #失效剔除
    eviction-interval-timer-in-ms: 30000
spring:
  application:
    name: eureka-server